// Strada Intelligence — Trading Terminal dashboard fixture.
// Captured verbatim from the live stradaintel.info/dashboard during the design phase
// (see docs/dashboard-redesign/handoff). Replace with live data adapter in Phase 2.

export const SI_DATA = {
  brand: {
    name: 'Strada Intelligence',
    tagline: 'Dubai Market Tracker',
    user: 'Kyle.Caruana',
    pageTitle: 'Dubai Property Intelligence',
  },
  filters: {
    areas: [
      'All areas',
      'Dubai Marina',
      'Downtown Dubai',
      'Palm Jumeirah',
      'Business Bay',
      'Jumeirah Village Circle',
      'Dubai Hills Estate',
      'Arabian Ranches',
    ],
    ranges: ['7d', '30d', '90d'],
    statusBanner: 'Client view · area filter active · refresh is admin-only',
    exportNote: 'Load intelligence before export for full report',
  },
  s01: {
    no: '01',
    title: 'Dubai Property Market — The Numbers',
    desc: 'Live transaction data from Dubai Land Department, rental yields, asking prices and the most active areas this week.',
    tabs: ['Sales Data', 'Rental Data'],
    eyebrow: 'HOW MANY DEALS ARE HAPPENING · Latest week',
    kpis: [
      { label: 'Properties Sold',   value: '1,842',    delta: '+12.3%', deltaLabel: 'vs last week', trend: 'up', period: 'Apr 14–21, 2026' },
      { label: 'Total Sales Value', value: 'AED 3.42B', delta: '+18.7%', deltaLabel: 'vs last week', trend: 'up', period: 'Apr 14–21, 2026' },
      { label: 'Average PSF',       value: 'AED 1,982', delta: '+2.1%',  deltaLabel: '30-day avg',   trend: 'up', period: '30-day avg' },
      { label: 'Rental Yield',      value: '6.8%',      delta: '+0.3%',  deltaLabel: 'gross annual', trend: 'up', period: 'gross annual' },
    ],
    psfTitle: 'Average Asking Price Per Square Foot',
    psfRows: [
      { label: 'Apartments', value: 'AED 1,982/sqft', delta: '+2.1%' },
      { label: 'Villas',     value: 'AED 1,418/sqft', delta: '+1.4%' },
    ],
    mixTitle: 'What Kind of Property Is Selling?',
    mix: [
      { label: 'Apartments', pct: 68 },
      { label: 'Villas',     pct: 19 },
      { label: 'Townhouses', pct: 9 },
      { label: 'Penthouses', pct: 4 },
    ],
    recentTitle: 'Recent sales transactions',
    recentSub: 'Last 25 by date',
    recent: [
      { date: 'Apr 21', area: 'Dubai Marina',    bldg: 'Marina Gate 2',        type: '2 Bed Apt', price: 'AED 3,450,000',  psf: '2,012' },
      { date: 'Apr 21', area: 'Downtown Dubai',  bldg: 'The Address Sky View', type: '1 Bed Apt', price: 'AED 2,890,000',  psf: '2,341' },
      { date: 'Apr 21', area: 'Palm Jumeirah',   bldg: 'One at Palm',          type: 'Penthouse', price: 'AED 18,500,000', psf: '4,820' },
      { date: 'Apr 20', area: 'Business Bay',    bldg: 'DAMAC Towers',         type: 'Studio',    price: 'AED 1,180,000',  psf: '1,672' },
      { date: 'Apr 20', area: 'Dubai Hills',     bldg: 'Park Heights',         type: '3 Bed Apt', price: 'AED 4,720,000',  psf: '1,802' },
      { date: 'Apr 20', area: 'JVC',             bldg: 'Bloom Towers',         type: '1 Bed Apt', price: 'AED 880,000',    psf: '998' },
      { date: 'Apr 19', area: 'Arabian Ranches', bldg: 'Saheel',               type: 'Villa',     price: 'AED 6,200,000',  psf: '1,210' },
      { date: 'Apr 19', area: 'Dubai Marina',    bldg: 'Cayan Tower',          type: '2 Bed Apt', price: 'AED 3,210,000',  psf: '1,978' },
    ],
  },
  verdict: {
    score: 3.9,
    label: 'Strong Market',
    sub: 'Most signals are healthy — a good time to hold and invest in Dubai',
    asOf: 'as of Apr 21, 2026',
  },
  s02: {
    no: '02',
    title: "What's Driving the Market?",
    desc: "Seven forces that determine where Dubai property prices go next — each searched, scored and explained in plain English. Green means it's helping your property value. Red means it's adding pressure.",
    pillars: [
      { id: 'region',    title: 'Is the Region Stable?',     q: 'Are conflicts or instability affecting investor confidence?', score: 4.2, summary: 'No active escalations. UAE risk index sits at multi-year lows; Western advisories are unchanged.' },
      { id: 'oil',       title: 'Gulf Oil Wealth',           q: 'Do Gulf states have money to invest in Dubai property?',      score: 3.8, summary: 'Brent at $82 — comfortably above the $65 floor. Sovereign wealth deployment continues.' },
      { id: 'companies', title: 'Dubai Company Health',      q: "Are Dubai's biggest property companies doing well?",          score: 3.5, summary: 'Emaar and DAMAC trading near 52-week highs. Backlog and sales velocity are strong.' },
      { id: 'mortgage',  title: 'Are Mortgages Affordable?', q: 'Are global interest rates working for or against buyers?',    score: 2.9, summary: 'EIBOR at 4.6%. Mortgage demand soft but stabilising as Fed signals 2026 cuts.' },
      { id: 'foreign',   title: 'Foreign Buyer Appetite',    q: 'Are buyers from India, China and abroad still active?',       score: 3.1, summary: 'Indian and Russian flows steady. Chinese buyer share recovering after a soft Q1.' },
      { id: 'tourism',   title: 'Tourism & People Moving',   q: 'Is Dubai still growing as a place to live and invest?',       score: 4.4, summary: 'DXB pax +9.4% YoY. Net new resident permits up double-digits — strong demand floor.' },
      { id: 'mood',      title: 'Property Market Mood',      q: 'How are buyers and sellers feeling about the market?',        score: 3.6, summary: 'Listings DOM falling. Asking-to-achieved spread tightening — healthy buyer urgency.' },
    ],
  },
  s03: {
    no: '03',
    title: 'Where the Money is Moving',
    desc: 'Top areas by transaction volume this week, paired with rental yield by property type.',
    areas: [
      { rank: 1, area: 'Dubai Marina',           vol: 842, psf: '1,982', trend: 'up' },
      { rank: 2, area: 'Downtown Dubai',          vol: 614, psf: '2,341', trend: 'up' },
      { rank: 3, area: 'Jumeirah Village Circle', vol: 508, psf: '987',   trend: 'flat' },
      { rank: 4, area: 'Business Bay',            vol: 391, psf: '1,543', trend: 'down' },
      { rank: 5, area: 'Dubai Hills Estate',      vol: 302, psf: '1,776', trend: 'up' },
      { rank: 6, area: 'Palm Jumeirah',           vol: 218, psf: '3,102', trend: 'up' },
      { rank: 7, area: 'Arabian Ranches',         vol: 154, psf: '1,204', trend: 'flat' },
    ],
    yields: [
      { label: 'Studio',    gross: 7.4 },
      { label: '1 Bed',     gross: 6.8 },
      { label: '2 Bed',     gross: 5.9 },
      { label: '3 Bed',     gross: 5.1 },
      { label: 'Villa',     gross: 4.3 },
      { label: 'Penthouse', gross: 3.8 },
    ],
    charts: {
      psf:    [1640, 1720, 1698, 1780, 1842, 1910, 1875, 1920, 1982],
      vol:    [920, 1040, 1120, 980, 1380, 1540, 1620, 1710, 1842],
      yld:    [5.8, 6.0, 6.2, 6.1, 6.4, 6.5, 6.6, 6.7, 6.8],
      labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
    },
  },
  s04: {
    no: '04',
    title: 'Warning Signs — Know When to Act',
    desc: 'Bookmark this page. If any of these occur, check the relevant column for what to do. Nothing on this list is currently triggered unless it glows red or amber.',
    cols: ['What to Watch For', 'Urgency Level', 'What to Do'],
    rows: [
      { watch: 'A confirmed military strike or attack inside UAE',         urgency: 'Act Today',     level: 'red',   action: 'Stop all new purchases immediately. Move to a cash-preferred position.' },
      { watch: 'US or UK government warns against travel to UAE',          urgency: 'Act Today',     level: 'red',   action: 'Western buyer demand will pause within 48 hours. Hold all listings.' },
      { watch: 'Strait of Hormuz blocked or disrupted',                    urgency: 'Act Today',     level: 'red',   action: 'Direct impact on UAE economy. Maximum defensive position — no new moves.' },
      { watch: "Dubai's biggest developer (Emaar) shows financial stress", urgency: 'Pause & Watch', level: 'amber', action: 'Stop buying off-plan projects. Switch to completed, rented properties only.' },
      { watch: 'Dubai airport visitor numbers drop 25%+ vs last year',     urgency: 'Pause & Watch', level: 'amber', action: 'Tourism demand is weakening. Short-let and holiday home property most at risk.' },
      { watch: 'Dubai property transaction volumes drop 30% for 2+ weeks', urgency: 'Pause & Watch', level: 'amber', action: 'Market has gone quiet. Price falls likely in 60–90 days. Hold any listings.' },
      { watch: 'Global stock markets crash 10%+ in a single week',         urgency: 'Pause & Watch', level: 'amber', action: 'International buyers pause immediately. Foreign demand drops for 4–8 weeks.' },
      { watch: 'Oil price stays below $65 for 2+ weeks',                   urgency: 'Keep Watching', level: 'watch', action: 'Gulf investors — your biggest buyer group — have less money. Monitor volumes.' },
      { watch: 'US stock market falls 10%+ over a month',                  urgency: 'Keep Watching', level: 'watch', action: 'Wealthy international buyers feel poorer. Demand from US/UK softens for 1–2 months.' },
      { watch: 'Major regional ceasefire or peace deal signed',            urgency: 'Opportunity',   level: 'green', action: 'Risk premium falls. Expect a fresh wave of GCC and Western buyer interest.' },
    ],
  },
  s05: {
    no: '05',
    title: 'Supporting data (stocks, rates)',
    desc: 'Reference numbers behind the scores. Collapsed by default — open if you want to see the underlying inputs.',
    rows: [
      { label: 'Brent crude (USD/bbl)', value: '$82.40',  delta: '+1.2%' },
      { label: 'EIBOR 3M',              value: '4.60%',   delta: '−0.05pp' },
      { label: 'US 10Y Treasury',       value: '4.18%',   delta: '+0.04pp' },
      { label: 'AED/USD',               value: '3.6725',  delta: 'flat' },
      { label: 'TASI (Saudi)',          value: '12,140',  delta: '+0.4%' },
      { label: 'DFM Index',             value: '5,210',   delta: '+0.6%' },
      { label: 'Emaar Properties',      value: 'AED 9.85', delta: '+1.8%' },
      { label: 'DAMAC',                 value: 'AED 2.74', delta: '+0.7%' },
    ],
  },
  s06: {
    no: '06',
    title: 'Morning checklist',
    desc: 'Five-minute routine. Open each link, glance, close — then start the day.',
    groups: [
      { group: 'Markets & Money',   items: [
        { label: 'Bloomberg Middle East',  href: '#' },
        { label: 'Reuters Gulf',           href: '#' },
        { label: 'WSJ Markets',            href: '#' },
        { label: 'CNBC Pre-Market',        href: '#' },
      ]},
      { group: 'Dubai Property',    items: [
        { label: 'Dubai Land Department',  href: '#' },
        { label: 'Property Monitor',       href: '#' },
        { label: 'Bayut MarketWatch',      href: '#' },
        { label: 'Property Finder Trends', href: '#' },
      ]},
      { group: 'Region & Risk',     items: [
        { label: 'UK FCO Travel Advice',     href: '#' },
        { label: 'US State Dept Advisories', href: '#' },
        { label: 'Reuters Middle East',      href: '#' },
        { label: 'Al Arabiya English',       href: '#' },
      ]},
      { group: 'Tourism & People',  items: [
        { label: 'DXB Daily Stats',        href: '#' },
        { label: 'GDRFA Resident Permits', href: '#' },
        { label: 'KHDA School Enrolments', href: '#' },
      ]},
    ],
  },
  footer: {
    line1: 'Strada Intelligence — Dubai Market Tracker',
    line2: 'Built by Kyle Caruana · Strada Real Estate · For clients only',
    contact: 'kyle@stradauae.com · +971 50 000 0000',
  },
};
